sonar.projectName=react-native-client
sonar.projectKey=react-native-client
sonar.sources=src
sonar.inclusions=**/*.ts,**/*.tsx
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/__tests__/**/*
sonar.links.ci=https://github.com/splitio/react-native-client
sonar.links.scm=https://github.com/splitio/react-native-client/actions
