name: ci
on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - development
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: npm CI
        run: npm ci

      - name: npm Check
        run: npm run check

      - name: npm Test
        run: npm run test -- --coverage

      - name: npm Build
        run: npm run build

      - name: SonarQube Scan (Push)
        if: github.event_name == 'push'
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONARQUBE_HOST }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
            -Dsonar.projectVersion=${{ env.VERSION }}

      - name: SonarQube Scan (Pull Request)
        if: github.event_name == 'pull_request'
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONARQUBE_HOST }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
            -Dsonar.projectVersion=${{ env.VERSION }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
